### ISSUE TITLE
Install failed with   P6opaque: no such attribute '$!storage'

### ISSUE THREAD

**Issue by szabgab** [css-raku/CSS-Grammar-raku#4]
```
$ panda install CSS::Grammar
==> Fetching CSS::Grammar
==> Building CSS::Grammar
==> Testing CSS::Grammar
t/parse-stylesheets.t .. ok
P6opaque: no such attribute '$!storage'
  in sub _display-string at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:53
  in method warning at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:64
  in method dropped-decl at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:101
  in regex dropped-decl at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:141
  in regex any-declaration at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS21.pm:52
  in regex declaration at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS21.pm:50
  in regex declaration-list at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS21.pm:49
  in sub parse-tests at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Test.pm:45
  in block <unit> at t/error-handling.t:24

t/error-handling.t ..... 
All 6 subtests passed 
t/css3-syntax.t ........ ok
P6opaque: no such attribute '$!storage'
  in method color:sym<hex> at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:221
  in regex color:sym<hex> at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:97
  in regex color at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:92
  in regex term1:sym<color> at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:116
  in regex term1 at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:111
  in regex term at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar.pm:109
  in regex expr at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:39
  in sub parse-tests at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Test.pm:45
  in block  at t/compat.t:44
  in block <unit> at t/compat.t:19

t/compat.t ............. 
All 390 subtests passed 
    (less 3 skipped subtests: 387 okay)
t/regex-tokens.t ....... ok
P6opaque: no such attribute '$!storage'
  in sub _display-string at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:53
  in method warning at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:64
  in method any-declaration at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/Actions.pm:315
  in regex any-declaration at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:36
  in regex declaration at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:35
  in regex declaration-list at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:34
  in regex declarations at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:27
  in regex ruleset at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:20
  in regex stylesheet at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:13
  in regex TOP at /Users/gabor/work/.panda-work/1445708122_1/lib/CSS/Grammar/CSS1.pm:9
  in block <unit> at t/parse-warnings.t:24

t/parse-warnings.t ..... 
No subtests run 

Test Summary Report
-------------------
t/error-handling.t   (Wstat: 0 Tests: 6 Failed: 0)
  Parse errors: No plan found in TAP output
t/compat.t           (Wstat: 0 Tests: 390 Failed: 0)
  Parse errors: No plan found in TAP output
t/parse-warnings.t   (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=6, Tests=656, 17 wallclock secs ( 0.25 usr  0.04 sys + 52.82 cusr  1.58 csys = 54.69 CPU)
Result: FAIL
test stage failed for CSS::Grammar: Tests failed
  in method install at /Users/gabor/work/rakudo/install/share/perl6/site/lib/Panda.pm:142
  in method resolve at /Users/gabor/work/rakudo/install/share/perl6/site/lib/Panda.pm:219
  in sub MAIN at /Users/gabor/work/rakudo/install/share/perl6/site/bin/panda:18
  in block <unit> at /Users/gabor/work/rakudo/install/share/perl6/site/bin/panda:145


Failure Summary
----------------
CSS::Grammar(
    *test stage failed for CSS::Grammar: Tests failed)
```

**Comment by dwarring** [comment]
Commit https://github.com/p6-css/perl6-CSS-Grammar/commit/ae10ff0d9dcaee74412db329687c6f20835609cf  introduces some minor work-arounds and marks some tests as todo. 

Looking like a rakudo issue - sometimes happening when calling regex related methods from actions methods.

**Comment by dwarring** [comment]
CSS::Module has similar issues. Interestingly CSS21 passes, however CSS3 fails, even without an actions method.
```
$ perl6 -I blib/lib -M CSS::Module::CSS21 -e'CSS::Module::CSS21.parse(q<{colr:redl}>, :rule<declarations> )'
$ perl6 -I blib/lib -M CSS::Module::CSS3 -e'CSS::Module::CSS3.parse(q<{color:red}>, :rule<declar
ations> )'
P6opaque: no such attribute '$!storage'
  in regex color:sym<current> at lib/CSS/Module/CSS3/Colors.pm:45
  in regex color at lib/CSS/Grammar.pm:92
  in regex expr-color at lib/CSS/Module/CSS21/Spec/Grammar.pm:141
  in regex  at /home/jachadley/git/perl6-CSS-Module/blib/lib/CSS/Module/CSS21/Spec/Grammar.pm.moarvm:1
  in regex val at lib/CSS/Specification/Terms.pm:8
  in regex decl:sym<color> at lib/CSS/Module/CSS21/Spec/Grammar.pm:140
  in regex decl at lib/CSS/Specification/Terms.pm:21
  in regex declaration at lib/CSS/Specification/Terms.pm:20
  in regex declaration-list at lib/CSS/Grammar/CSS21.pm:49
  in regex declarations at lib/CSS/Grammar/CSS21.pm:42
  in block <unit> at -e:1
```

**Comment by dwarring** [comment]
Bug still present in Rakudo 2017.04.3

**Comment by dwarring** [comment]
See Rakudo issue https://github.com/rakudo/rakudo/issues/1407 which partially addresses this issue and points to the root cause.

**Comment by Altai-man** [comment]
The original issue was fixed, so maybe this can be closed?

**Comment by dwarring** [comment]
There is actually still an issue, on latest bleed, when I try to uncomment the following:
```
$ git diff lib/CSS/Grammar/Actions.rakumod
diff --git a/lib/CSS/Grammar/Actions.rakumod b/lib/CSS/Grammar/Actions.rakumod
index 68ab931..5999727 100644
--- a/lib/CSS/Grammar/Actions.rakumod
+++ b/lib/CSS/Grammar/Actions.rakumod

@@ -140,11 +139,11 @@ class CSS::Grammar::Actions
        my Str $name = [~] flat @<nmchar>.map( *.ast);
        make $.token( $name, :type(CSSValue::NameComponent));
     }
-    method num($/)   { my $num = $/.Rat;
-                       make $.token( $num % 1
-                                     ?? $num
-                                     !! $num.Int, :type(CSSValue::NumberComponent))
-                     }
+    method num($/)   {
+        my $num = $/.Rat;
+        $num .= Int if $num %% 1;
+        make $.token($num, :type(CSSValue::NumberComponent));
+    }
     method uint($/)  { make $/.Int }
     method op($/)    { make $/.lc  }
 
```

Gives:
```
$ prove -e'raku -I .' t/compat.t
t/compat.t .. 154/? P6opaque: no such attribute '$!storage' on type CSSValue in a Hash when trying to bind a value
  in method color:sym<hex> at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar/Actions.rakumod (CSS::Grammar::Actions) line 215
  in regex color:sym<hex> at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar.rakumod (CSS::Grammar) line 94
  in regex color at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar.rakumod (CSS::Grammar) line 89
  in regex term1:sym<color> at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar.rakumod (CSS::Grammar) line 113
  in regex term1 at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar.rakumod (CSS::Grammar) line 108
  in regex term at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar.rakumod (CSS::Grammar) line 106
  in regex expr at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar/CSS1.rakumod (CSS::Grammar::CSS1) line 39
  in sub parse-tests at /home/david/git/CSS-Grammar-raku/lib/CSS/Grammar/Test.rakumod (CSS::Grammar::Test) line 42
  in block  at t/compat.t line 44
  in block <unit> at t/compat.t line 19

t/compat.t .. Dubious, test returned 1 (wstat 256, 0x100)
All 399 subtests passed 
	(less 3 skipped subtests: 396 okay)

Test Summary Report
-------------------
t/compat.t (Wstat: 256 Tests: 399 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=399,  8 wallclock secs ( 0.15 usr  0.02 sys +  9.52 cusr  0.33 csys = 10.02 CPU)
Result: FAIL
```
